/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kanesk06 (https://sketchfab.com/kanesk06)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-chair-grey-cushioned-c39430b3f91b43f7937174a9c27998f1
Title: Gaming Chair - Grey Cushioned
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GamingChair(props) {
  const { nodes, materials } = useGLTF("models/gamingChairGrey.glb");
  const group = useRef();

  return (
    <group {...props} ref={group} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.phongE2}
      />
    </group>
  );
}

useGLTF.preload("models/gamingChairGrey.glb");
